---
title: "libr"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{libr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
  
The **libr** package brings the concepts of data libraries, data 
dictionaries, and data steps to R.  

* A **data library** is an object used to define 
and manage an entire directory of data files.  
* A **data dictionary** is a data 
frame full of information about a data library, data frame, or tibble. 
* A **data step** is a mechanism to perform row-by-row processing of data.

These concepts have been available in SAS® software for decades. 
But they have not been available in R ... until now!

The **libr** package also includes an enhanced equality operator to
make comparisons between columns less error-prone.

### Key Functions

The above concepts are implemented in the **libr** package with four key 
functions. They are:

* `libname()`: Creates a data library
* `dictionary()`: Creates a data dictionary 
* `datastep()`: Performs row-by-row processing of data
* `%eq%`: An infix operator to check equality between objects

### Library Management Functions
There are several additional functions related to libraries.
These functions allow you to easily manage the data in your library.
The functions are:

* `lib_load()`: Loads a library into the workspace
* `lib_unload()`: Unloads a library from the workspace
* `lib_sync()`: Synchronizes the workspace with the library list
* `lib_write()`: Writes library data to the file system
* `lib_add()`: Adds data to a library
* `lib_replace()`: Replaces data in a library
* `lib_remove()`: Removes data from a library
* `lib_copy()`: Copies a data library
* `lib_delete()`: Deletes a data library
* `lib_info()`: Returns a data frame of information about the library
* `lib_path()`: Returns the path of a data library
* `lib_size()`: Returns the size of the data library in bytes

### Import Specs 

Special functions are needed when you want to control how the columns
in your data files are imported.  These functions allow you to
define an `import_spec` that controls the data type of each column. 
The import specs can even be saved and reused for future imports.

The functions related to import specs are as follows:

* `specs()`: Define a import specs collection for a library
* `import_spec()`: Define an import spec for a specific data file
* `write.specs()`: Writes a specs collection to the file system
* `read.specs()`: Reads a specs file from the file system


### Next Steps 

For next steps, please review the examples provided in the articles
section of this web site.  Those articles include:

* [Basic Library Operations](https://libr.r-sassy.org/articles/libr-basics.html)
* [Library Management](https://libr.r-sassy.org/articles/libr-management.html)
* [Data Step Operations](https://libr.r-sassy.org/articles/libr-datastep.html)
* [Enhanced Equality](https://libr.r-sassy.org/articles/libr-eq.html)



