# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bychanges <- function(dat) {
    .Call('_libr_bychanges', PACKAGE = 'libr', dat)
}

byfirst <- function(dat) {
    .Call('_libr_byfirst', PACKAGE = 'libr', dat)
}

bylast <- function(dat) {
    .Call('_libr_bylast', PACKAGE = 'libr', dat)
}

getsigs <- function(dat) {
    .Call('_libr_getsigs', PACKAGE = 'libr', dat)
}

